%x docstring

\"					{BEGIN(docstring); LexString=""; }
<docstring>\"		{BEGIN(INITIAL); yylval.o=new Str(LexString); return DOC; }
<docstring>\\n		{LexString+='\n';}
<docstring>\\t		{LexString+='\t';}
<docstring>\n		{LexString+=yytext[0];}
<docstring>\\.		{LexString+=yytext[1];}
<docstring>.		{LexString+=yytext[0];}

<lexstring>\\n		{LexString+='\n';}
<lexstring>\\t		{LexString+='\t';}
<lexstring>\n		{LexString+=yytext[0];}
<lexstring>\\.		{LexString+=yytext[1];}
